# Stage 1 – Build React App
FROM node:22-alpine AS builder

WORKDIR /app/

# Copy package.json & lockfile
COPY frontend/package*.json ./

# Install dependencies ignoring optional peer deps
RUN npm install --legacy-peer-deps

COPY frontend/ ./
# Build frontend
RUN npm run build

# Stage 2 – Serve with Nginx
FROM nginx:alpine

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
